# To implement
# - For YEEES: one node only, but implement endogeneous capital costs
# - regionalization of generation capacities via fixed distribution share (or fixed autarky level - no!)
# - calculation of regionalized annual revenues 
# - regionalized adaptation of capital costs
# - demand elasticity for a smoother price duration curve: https://www.sciencedirect.com/science/article/pii/S014098832500307X
# - Value of Lost Load (VoLL) to prevent very high scarcity prices
# - Demand data from the ENTSO-E ERAA dataset (Demand Data/Gross demand/DE00_Demand_gross_2030.csv) (There will be someone at YEEES who works on realistic demand curve projections)
# - Let it run for different CO2 prices to check development of importance of CfDs in the ongoing transition

# Open questions:
# - How to replace the whole sector coupling with just fixed demand assumptions



# This is the version used for the draft paper without updated capital costs

logging:
  level: INFO
solve_network: solve

run: 
  name: "2030_without_CfD_check"
  scenarios:
    enable: false
  shared_cutouts: true 

foresight: overnight # i.e., greenfield approach

scenario:
  clusters:
  - 1 # 13 # One per federal state (excl. city states)
  technology: [onwind, offwind-ac, offwind-dc, solar]
  opts:
  - EP # , EQ0.5]
  # - onwind+c0.5 # This reduces capital costs of onwind to 50 % of its original value
  # - offwind-ac+c0.5 # This reduces capital costs of offwind-ac to 50 % of its original value
  # - offwind-dc+c0.5 # This reduces capital costs of offwind-dc to 50 % of its original value
  # - solar+c0.5 # This reduces capital costs of solar to 50 % of its original value
  # - hydro+c0.5 # This reduces capital costs of hydro to 50 % of its original value # Include hydro in CfD? 
  # - EP # Add cost for a carbon-dioxide price configured in costs: emission_prices: co2 to marginal_cost of generators (other emission types listed in network.carriers possible as well)
  # - CCL # Add minimum and maximum levels of generator nominal capacity per carrier for individual countries. These can be specified in the file linked at electricity: agg_p_nom_limits in the configuration. File defaults to data/agg_p_nom_minmax.csv.
  # - EQ0.5 # Require each country or node to on average produce a minimal share of its total consumption itself. Example: EQ0.5c demands each country to produce on average at least 50% of its consumption; EQ0.5 demands each node to produce on average at least 50% of its consumption.
  planning_horizons: # Demand projections for sector-coupling only
  - 2030

countries:
- DE

snapshots:
  start: "2004-01-01" # "1988-01-01"
  end: "2004-01-08"
  inclusive: 'left'

enable:
  # retrieve: false
  build_cutout: false
  retrieve_cutout: false

electricity:
  extendable_carriers:
    Generator: [solar, solar-hsat, onwind, offwind-ac, offwind-dc, offwind-float] #, nuclear, oil, OCGT, CCGT, coal, lignite, geothermal, biomass]
    StorageUnit: [battery, H2]
    Store: [battery, H2]
    Link: [H2 pipeline]
  # everywhere_powerplants: [nuclear, oil, OCGT, CCGT, coal, lignite, geothermal, biomass]
  conventional_carriers: [nuclear, oil, OCGT, CCGT, coal, lignite, geothermal, biomass] # Adds existing conventional power plants from powerplants.csv
  renewable_carriers: [solar, onwind, offwind-ac, offwind-dc, offwind-float, hydro] # Includes listed renewable generator types in optimization

atlite:
  cutout_directory: cutouts
  default_cutout: de-2004_12-era5
#   nprocesses: 16
#   show_progress: false
  cutouts:
    # use 'base' to determine geographical bounds and time span from config
    # base:
      # module: era5
    # de-2004_13-era5:
    #   module: [era5] # in priority order
    #   x: [5., 16.] # Restrict to Germany
    #   y: [47., 56.]
    #   dx: 1.0 #0.3
    #   dy: 1.0 #0.3
    #   time: ["2004-01-01", "2013-01-31"]
      # features: [] 
      # sarah_dir: ""
    # pass

# sector:
#   regional_co2_sequestration_potential: 
#     enable: false # To prevent a bug
#   gas_network: false # Should not matter for copperplate simulation
#   gas_distribution_grid: false # ""
  

costs:
  year: 2030
  emission_prices:
    enable: true
    co2: 100

clustering: 
  mode: busmap # administrative # Uses NUTS3 regions for clustering (Kreisebene) 
  administrative:
    level: 1
  focus_weights: false
  # copperplate_regions: [DE]
  temporal:
    resolution_elec: false # Can re-sample the resultion to 'nH' by averaging over n hours

# solving:
  # options:
    # noisy_costs: true

solver:
  name: gurobi

plotting:
  map:
    boundaries: [5, 16, 47, 56] # Germany
  balance_timeseries:
    monthly: false