logging:
  level: INFO
solve_network: solve

results_dir: 'results\test_v2'

run: 
  name: "2030_without_CfD_test_v2"
  scenarios:
    enable: false
  shared_cutouts: true 

scenario:
  clusters:
  - 2
  technology: [onwind, offwind-ac, offwind-dc, solar]
  opts:
  - ''
  # - onwind+c0.5 # This reduces capital costs of onwind to 50 % of its original value
  # - offwind-ac+c0.5 # This reduces capital costs of offwind-ac to 50 % of its original value
  # - offwind-dc+c0.5 # This reduces capital costs of offwind-dc to 50 % of its original value
  # - solar+c0.5 # This reduces capital costs of solar to 50 % of its original value
  # - hydro+c0.5 # This reduces capital costs of hydro to 50 % of its original value # Include hydro in CfD? 
  # - EP # Add cost for a carbon-dioxide price configured in costs: emission_prices: co2 to marginal_cost of generators (other emission types listed in network.carriers possible as well)
  # - CCL # Add minimum and maximum levels of generator nominal capacity per carrier for individual countries. These can be specified in the file linked at electricity: agg_p_nom_limits in the configuration. File defaults to data/agg_p_nom_minmax.csv.
  # - EQ # Require each country or node to on average produce a minimal share of its total consumption itself. Example: EQ0.5c demands each country to produce on average at least 50% of its consumption; EQ0.5 demands each node to produce on average at least 50% of its consumption.
  # planning_horizons: # Demand projections for sector-coupling only
  # - 2030

countries:
- DE

# snapshots:
#   start: "2012-01-01" # "1988-01-01"
#   end: "2013-12-31"
#   inclusive: 'left'

# electricity:
#   renewable_carriers: [solar, onwind, offwind-ac, offwind-dc]

atlite:
#   cutout_directory: cutouts
#   default_cutout: europe-2013-sarah3-era5
#   nprocesses: 16
#   show_progress: false
  cutouts:
#     # use 'base' to determine geographical bounds and time span from config
#     # base:
#       # module: era5
    europe-2013-sarah3-era5:
#       module: [sarah, era5] # in priority order
#       x: [-12., 42.]
#       y: [33., 72.]
      dx: 1.0 #0.3
      dy: 1.0 #0.3
#       time: ["2013-01-01", "2014-12-31"]
#       # features: [] 
#       # sarah_dir: ""

sector:
  regional_co2_sequestration_potential: 
    enable: false
  gas_network: false # Should not matter for copperplate simulation
  gas_distribution_grid: false # ""
  

costs:
  year: 2030
  emission_prices:
    enable: true
    co2: 100

clustering: 
  mode: busmap # administrative # Uses NUTS3 regions for clustering (Kreisebene) 
  administrative:
    level: 1
  focus_weights: false
  copperplate_regions: [DE]

solver:
  name: gurobi